version: '2'
services:
  pihole_influx:
    build: .
    container_name: pihole_influx
    environment:
      - INFLUXDB_SERVER=172.0.0.1
      - INFLUXDB_PORT=8086
      - INFLUXDB_USERNAME=username
      - INFLUXDB_PASSWORD=password
      - INFLUXDB_DATABASE=dockerhubstats
      - DELAY=600
      - DOCKERHUB_IMAGES=pluim003/dockerhub_influx,pluim003/pihole_unbound
